In [1]:
import numpy as np

In [2]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)

In [3]:
print(data)

[[76 30 20 53  1]
 [10 23 93 88 94]
 [28 30 64 19 14]
 [74 35 25 59 69]
 [72 82 68 82 76]]


#### Matrix manipulation - Swap the second and fourth rows of the data matrix.

In [4]:
data[[1, 3]] = data[[3, 1]]

In [5]:
print(data)

[[76 30 20 53  1]
 [74 35 25 59 69]
 [28 30 64 19 14]
 [10 23 93 88 94]
 [72 82 68 82 76]]


#### Normalization - Normalize all the elements in the data matrix such that they are scaled to range between 0 and 1.

In [6]:
print(data / (100-0))

[[0.76 0.3  0.2  0.53 0.01]
 [0.74 0.35 0.25 0.59 0.69]
 [0.28 0.3  0.64 0.19 0.14]
 [0.1  0.23 0.93 0.88 0.94]
 [0.72 0.82 0.68 0.82 0.76]]


#### Z-score normalization - Standardize the data matrix using Z-score normalization. That is, all the elements should be scaled to have a mean* of 0 and a standard deviation of 1. Z-score is calculated as (X - mean) / std.

In [7]:
the_mean = np.mean(data)
rescaled = data - the_mean
print(f'{np.average(rescaled):.14f}')
rescaled = rescaled / 100
print(rescaled)

0.00000000000000
[[ 0.246 -0.214 -0.314  0.016 -0.504]
 [ 0.226 -0.164 -0.264  0.076  0.176]
 [-0.234 -0.214  0.126 -0.324 -0.374]
 [-0.414 -0.284  0.416  0.366  0.426]
 [ 0.206  0.306  0.166  0.306  0.246]]


#### Array splitting - Reshape the data matrix into a vector (Hint: use np.ravel) and split this array into five equal-sized sub-arrays.

In [8]:
raveled = np.ravel(data)

In [9]:
print(np.split(raveled,5))

[array([76, 30, 20, 53,  1]), array([74, 35, 25, 59, 69]), array([28, 30, 64, 19, 14]), array([10, 23, 93, 88, 94]), array([72, 82, 68, 82, 76])]


#### Dot product - Create two vectors of size 5 with any values. Compute the dot product of the two vectors*

In [10]:
vector1 = np.array(np.random.randint(1, 10, size=5))
vector2 = np.array(np.random.randint(1, 10, size=5))

In [11]:
print(np.dot(vector1, vector2))

77


In [12]:
data2 = np.array(np.random.randint(1, 100, size=9)).reshape(3,3)

In [13]:
print(data2)

[[32 25 79]
 [92 89 54]
 [86 86 44]]


In [14]:
print(np.dot(data[:3,:3], data2))

[[6912 6290 8504]
 [7738 7115 8836]
 [9160 8874 6648]]


#### Inverse of a matrix - Create a 3x3 identity matrix*, multiply it with 2 and compute its inverse.

In [15]:
iden = np.eye(3)

In [16]:
iden = iden * 2

In [17]:
print(np.linalg.inv(iden))

[[0.5 0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  0.5]]


#### Eigenvalues and eigenvectors - For the first 3x3 part of the data matrix, compute the eigenvalues and eigenvectors*.

In [18]:
print(np.linalg.eig(data[:3,:3]))

EigResult(eigenvalues=array([126.94428874,  45.09289614,   2.96281512]), eigenvectors=array([[-0.57380587, -0.34044749,  0.28595479],
       [-0.61031506, -0.25298538, -0.90539612],
       [-0.546134  ,  0.90559036,  0.31382754]]))


#### Find missing values - Replace random 5 elements in the data matrix with np.nan. Find the indices of the missing values.

In [37]:
np.dtype(data[0][0])
data_float = data.astype('float32')
print(data_float)

[[76. 30. 20. 53.  1.]
 [74. 35. 25. 59. 69.]
 [28. 30. 64. 19. 14.]
 [10. 23. 93. 88. 94.]
 [72. 82. 68. 82. 76.]]


In [38]:
data_float = data_float.ravel() 

In [39]:
np.random.randint(low = 0, high = 25, size=(5))

array([10, 18,  4,  9,  2])

In [40]:
rand_idx = np.random.randint(low = 0, high = 25, size=(5))

In [41]:
data_float[rand_idx] = np.nan

In [47]:
data_float = data_float.reshape(5,5)

In [48]:
print(data_float)

[[76.  30.  20.  53.   1. ]
 [74.  53.6 25.  59.  69. ]
 [28.  30.  64.  19.  53.6]
 [53.6 23.  93.  88.  94. ]
 [53.6 53.6 68.  82.  76. ]]


In [43]:
print(np.where(np.isnan(data_float )))

(array([ 6, 14, 15, 20, 21], dtype=int64),)


#### Replace missing values - Replace the missing values in the data matrix with the mean of the matrix (ignoring the missing values while computing the mean).

In [44]:
mean_data_float = np.nanmean(data_float)

In [45]:
data_float[np.isnan(data_float)] = mean_data_float

In [49]:
print(data_float)

[[76.  30.  20.  53.   1. ]
 [74.  53.6 25.  59.  69. ]
 [28.  30.  64.  19.  53.6]
 [53.6 23.  93.  88.  94. ]
 [53.6 53.6 68.  82.  76. ]]
