# Exercise 1

#### Import the numpy package under the name np.

In [1]:
import numpy as np

#### Create a vector* of zeros with size 10 using np.zeros().

In [2]:
zero_arr = np.zeros(10)

In [3]:
print(zero_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Compute the memory size* of any array. 

In [4]:
print(zero_arr.itemsize * len(zero_arr))

80


#### Retrieve the documentation of the numpy add function from the command line.

In [10]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### Create a vector with values ranging from 10 to 49 using np.arange().

In [7]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### Reverse a vector so the first element becomes last (Hint: Use slicing).

In [8]:
print(vector[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### Create a 3x3 matrix* with values ranging from 0 to 8 using np.reshape().

In [11]:
print(np.arange(9).reshape((3, 3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Find indices of non-zero elements from [1,2,0,0,4,0] using np.nonzero().

In [12]:
print(np.nonzero(np.array([1,2,0,0,4,0])))

(array([0, 1, 4], dtype=int64),)


#### Create a 3x3 identity matrix* using np.eye()

In [14]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Create a 5x5 matrix with row values ranging from 0 to 4. The output should be a matrix where each row is [0, 1, 2, 3, 4].

In [15]:
print(np.tile(np.array([0,1,2,3,4]), (5,1)))

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [16]:
print(np.linspace(0, 1, 11, False)[1:])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### Create a random vector of size 10 and sort it.

In [78]:
randvec = np.random.rand(1,10)
print(np.sort(randvec))

[[0.06124838 0.11372776 0.13016802 0.2116195  0.42319915 0.57292553
  0.61962583 0.6932795  0.74488589 0.97624972]]


#### Print the minimum and maximum representable value for each numpy scalar type* (int8, int32, int64, float32, float64).

In [18]:
ii8 = np.iinfo(np.int8)
ii32 = np.iinfo(np.int32)
ii64 = np.iinfo(np.int64)
if32 = np.finfo(np.float32)
if64 = np.finfo(np.float64)
print(f"min = {ii8.min} max = {ii8.max}")
print(f"min = {ii32.min} max = {ii32.max}")
print(f"min = {ii64.min} max = {ii64.max}")
print(f"min = {if32.min} max = {if32.max}")
print(f"min = {if64.min} max = {if64.max}")

min = -128 max = 127
min = -2147483648 max = 2147483647
min = -9223372036854775808 max = 9223372036854775807
min = -3.4028234663852886e+38 max = 3.4028234663852886e+38
min = -1.7976931348623157e+308 max = 1.7976931348623157e+308


#### How to convert a float (32 bits) array into an integer (32 bits) in place? Use np.ndarray.astype.

In [22]:
x = np.array([1, 2.321, 2.5])
x.astype(ii32)

array([1, 2, 2])

#### Subtract the mean* of each row of a matrix. Use np.mean with axis=1.

In [26]:
matrix_dec = np.tile(np.array([0,1,2,3,4]), (5,1))
print(matrix_dec)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [25]:
print(matrix_dec - np.mean(matrix_dec, 1))

[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


#### How to sort an array by the nth column? Use np.argsort.

In [65]:
vector = np.random.randint(10,size=15)

In [66]:
vector = vector.reshape(3,5)

In [67]:
sorted_matrix = vector[vector[:,1].argsort()]
print(sorted_matrix)

[[2 3 4 3 6]
 [3 3 3 8 9]
 [7 5 4 3 0]]


#### How to swap two rows of an array? You can do this using array indexing.

In [68]:
vector[[0,1]] = vector[[1,0]]
print(vector)

[[2 3 4 3 6]
 [7 5 4 3 0]
 [3 3 3 8 9]]


#### Given an array C that is a bincount*, how to produce an array A such that np.bincount(A) == C? Use np.repeat.

In [70]:
binc = np.random.randint(10,size=15)

In [71]:
arrc = np.bincount(binc)

In [72]:
print(binc)
print(arrc)

[4 5 9 3 9 9 3 4 8 4 2 4 7 7 1]
[0 1 1 2 4 1 0 2 1 3]


In [74]:
eq = np.repeat(np.arange(len(arrc)), arrc)

print(eq)

[1 2 3 3 4 4 4 4 5 7 7 8 9 9 9]


In [79]:
print(np.array_equal(eq, np.sort(binc)))

True
